[tool.poetry]
name = "custom"
version = "0.1.0"
description = "Custom python utilities."
authors = ["Max Fatouros <max.fatouros@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
